# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/z7_adder_design/z7_adder_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==z7_adder_design || ORIG_REF_NAME==z7_adder_design} -quiet] -quiet

# IP: bd/z7_adder_design/ip/z7_adder_design_processing_system7_0_0/z7_adder_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==z7_adder_design_processing_system7_0_0 || ORIG_REF_NAME==z7_adder_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/z7_adder_design/ip/z7_adder_design_adder_ip_0_0/z7_adder_design_adder_ip_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==z7_adder_design_adder_ip_0_0 || ORIG_REF_NAME==z7_adder_design_adder_ip_0_0} -quiet] -quiet

# IP: bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/z7_adder_design_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==z7_adder_design_axi_smc_0 || ORIG_REF_NAME==z7_adder_design_axi_smc_0} -quiet] -quiet

# IP: bd/z7_adder_design/ip/z7_adder_design_rst_ps7_0_50M_0/z7_adder_design_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==z7_adder_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==z7_adder_design_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/z7_adder_design_ooc.xdc
