# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "E:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.runs/synth_1/z7_adder_design_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 8
set_param general.usePosixSpawnForFork 1
set_param synth.incrementalSynthesisCache C:/Users/karol/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-17776-ROG-STRIX-Z790/incrSyn
set_param checkpoint.writeSynthRtdsInDcp 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.cache/wt [current_project]
set_property parent.project_path E:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part microphase:z7-nano-7020:part0:1.0 [current_project]
set_property ip_repo_paths e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/adder_ip [current_project]
update_ip_catalog
set_property ip_output_repo e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/hdl/z7_adder_design_wrapper.v
add_files E:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.srcs/sources_1/bd/z7_adder_design/z7_adder_design.bd
set_property used_in_implementation false [get_files -all e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_processing_system7_0_0/z7_adder_design_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_adder_ip_0_0/constraints/adder_ip_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_1/bd_cdfb_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_5/bd_cdfb_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_6/bd_cdfb_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_7/bd_cdfb_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_8/bd_cdfb_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_9/bd_cdfb_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_10/bd_cdfb_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_11/bd_cdfb_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/smartconnect.xdc]
set_property used_in_implementation false [get_files -all e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_rst_ps7_0_50M_0/z7_adder_design_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_rst_ps7_0_50M_0/z7_adder_design_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/z7_adder_design_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental E:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.srcs/utils_1/imports/synth_1/z7_adder_design_wrapper.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top z7_adder_design_wrapper -part xc7z020clg400-2
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef z7_adder_design_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file z7_adder_design_wrapper_utilization_synth.rpt -pb z7_adder_design_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
