# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.srcs/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/z7_adder_design_axi_smc_0.xci
# IP: The module: 'z7_adder_design_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/bd_cdfb.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_0/bd_cdfb_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_1/bd_cdfb_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_2/bd_cdfb_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_3/bd_cdfb_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_4/bd_cdfb_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_5/bd_cdfb_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_6/bd_cdfb_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_7/bd_cdfb_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_8/bd_cdfb_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_9/bd_cdfb_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_10/bd_cdfb_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_11/bd_cdfb_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_12/bd_cdfb_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_1/bd_cdfb_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_5/bd_cdfb_s00a2s_0_ooc.xdc

# XDC: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_6/bd_cdfb_sarn_0_ooc.xdc

# XDC: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_7/bd_cdfb_srn_0_ooc.xdc

# XDC: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_8/bd_cdfb_sawn_0_ooc.xdc

# XDC: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_9/bd_cdfb_swn_0_ooc.xdc

# XDC: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_10/bd_cdfb_sbn_0_ooc.xdc

# XDC: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_11/bd_cdfb_m00s2a_0_ooc.xdc

# XDC: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'z7_adder_design_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'z7_adder_design_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.srcs/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/z7_adder_design_axi_smc_0.xci
# IP: The module: 'z7_adder_design_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/bd_cdfb.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_0/bd_cdfb_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_1/bd_cdfb_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_2/bd_cdfb_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_3/bd_cdfb_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_4/bd_cdfb_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_5/bd_cdfb_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_6/bd_cdfb_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_7/bd_cdfb_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_8/bd_cdfb_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_9/bd_cdfb_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_10/bd_cdfb_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_11/bd_cdfb_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_12/bd_cdfb_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_1/bd_cdfb_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_5/bd_cdfb_s00a2s_0_ooc.xdc

# XDC: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_6/bd_cdfb_sarn_0_ooc.xdc

# XDC: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_7/bd_cdfb_srn_0_ooc.xdc

# XDC: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_8/bd_cdfb_sawn_0_ooc.xdc

# XDC: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_9/bd_cdfb_swn_0_ooc.xdc

# XDC: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_10/bd_cdfb_sbn_0_ooc.xdc

# XDC: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/bd_0/ip/ip_11/bd_cdfb_m00s2a_0_ooc.xdc

# XDC: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'z7_adder_design_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'z7_adder_design_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
