domain_path: E:\dokumenty\hobby\informatyka\projects\z7-nano-7020\examples\z7_adder_platf\export\z7_adder_platf\sw\standalone_ps7_cortexa9_0
app_src_dir: E:\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
lang: c
