# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.srcs/sources_1/bd/z7_adder_design/ip/z7_adder_design_adder_ip_0_0/z7_adder_design_adder_ip_0_0.xci
# IP: The module: 'z7_adder_design_adder_ip_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_adder_ip_0_0/constraints/adder_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'z7_adder_design_adder_ip_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.srcs/sources_1/bd/z7_adder_design/ip/z7_adder_design_adder_ip_0_0/z7_adder_design_adder_ip_0_0.xci
# IP: The module: 'z7_adder_design_adder_ip_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/dokumenty/hobby/informatyka/projects/z7-nano-7020/examples/z7_adder_proj/z7_adder_proj.gen/sources_1/bd/z7_adder_design/ip/z7_adder_design_adder_ip_0_0/constraints/adder_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'z7_adder_design_adder_ip_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
